modified to play nice with dynamic paper jar name, quoted per ShellCheck

diff --git a/scripts/signEULA b/scripts/signEULA
--- a/scripts/signEULA
+++ b/scripts/signEULA
@@ -1,15 +1,15 @@
 #!/bin/sh
 if [ $# -ne 2 ]; then
 	echo "Wrong number of arguments to signEULA" 1>&2
-  echo "Needs path to paper.jar, omitting final slash, and EULA signing value" 1>&2
+  echo "Needs path to paper jar (with filename) and EULA signing value" 1>&2
 	exit 2
 fi
 path_to_jar=$1
 eula_sign=$2
-cd $path_to_jar || exit 1
+cd "$path_to_jar" || exit 1
 if [ ! -e eula.txt ]; then
-	if [ ! -e paper.jar ]; then
-		echo "Wrong directory? paper.jar not found at $path_to_jar/paper.jar" 1>&2
+	if [ ! -e "$path_to_jar" ]; then
+		echo "Wrong directory? $path_to_jar not found" 1>&2
 		exit 1
 	fi
 	java -jar paper.jar
