ENV must be declared in each FROM, var names must match to work

diff --git a/scripts/signEULA b/scripts/signEULA
--- a/scripts/signEULA
+++ b/scripts/signEULA
@@ -1,18 +1,18 @@
 #!/bin/sh
-if [ $# -ne 3 ]; then
+if [ $# -ne 2 ]; then
 	echo "Wrong number of arguments to signEULA" 1>&2
-  echo "Needs path to paper jar, filename, and EULA signing value" 1>&2
+  echo "Needs path to jar and EULA signing value" 1>&2
 	exit 2
 fi
 path_to_jar=$1
-jar_name=$2
-eula_sign=$3
+eula_sign=$2
 cd "${path_to_jar}" || exit 1
 if [ ! -e eula.txt ]; then
-	if [ ! -e "${jar_name}" ]; then
-		echo "Wrong directory? ${path_to_jar}/${jar_name} not found" 1>&2
+	if [ ! -e "${PAPER_FILENAME}" ]; then
+		echo "Wrong directory? ${path_to_jar}/${PAPER_FILENAME} not found" 1>&2
 		exit 1
 	fi
-	java -jar paper.jar
+	java -jar "${PAPER_FILENAME}"
 fi
 sed -i "s:false:$eula_sign:g" eula.txt
+exit 0
